name: CI/CD

on:
  [push]

jobs:
  blog: 
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # 拉取仓库代码
      - uses: actions/setup-node@v2 # 设置 node.js 环境
      - name: Cache node_modules # 缓存 node_modules，提高编译速度
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Init Node.js
        run: |
          npm install
          echo "init node successful"
      - name: Install Hexo-cli # 安装 Hexo
        run: |
          npm install -g hexo-cli --save
          echo "install hexo successful"
      - name: Build
        run: |
          hexo clean
          hexo g
          echo "build blog successful"
      - name: Deploy
        env:
          SSH_PRIVATE: ${{ secrets.SSH_PRIVATE }}
          GIT_NAME: Triority
          GIT_EMAIL: triority@qq.com
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "Triority"
          git config --global user.email "triority@qq.com"
          hexo deploy

      - run: echo "Deploy Successful!"
